"""
parole.py — Versets bibliques liés aux statuts de prédiction
Auteur : Sossou Kouamé
L'administrateur peut ajouter librement des versets dans chaque catégorie.
"""

import random
import re

# ═══════════════════════════════════════════════════════════════════
#  SIGNATURE FINALE — ajoutée à la fin de chaque parole
# ═══════════════════════════════════════════════════════════════════
SIGNATURE = (
    "\n\n🙏 _Dieu est au contrôle_"
    "\n— **Sossou Kouamé** prediction 🔥"
)

# ═══════════════════════════════════════════════════════════════════
#  ✅0️⃣  GAGNÉ DIRECT — Grâce immédiate de Dieu
# ═══════════════════════════════════════════════════════════════════
PAROLES_GAGNE_R0 = [
    "🙌 « *Car c'est par grâce que vous êtes sauvés, par le moyen de la foi. Et cela ne vient pas de vous, c'est le don de Dieu.* » — Éph 2:8",
    "🌟 « *L'Éternel t'a accordé sa faveur avant même que tu demandes.* » — És 65:24",
    "🎯 « *Avant qu'ils appellent, Je répondrai ; ils parleront encore que J'aurai exaucé.* » — És 65:24",
    "⚡ « *Ce n'est pas à celui qui court, ni à celui qui fait des efforts, mais à Dieu qui fait grâce.* » — Rom 9:16",
    "🔥 « *Dieu a fait en sorte que tout concourt au bien de ceux qui l'aiment.* » — Rom 8:28",
    "🌈 « *Il a béni chacun de nous en Christ de toute bénédiction spirituelle.* » — Éph 1:3",
    "✨ « *La bonté et la grâce me suivront tous les jours de ma vie.* » — Ps 23:6",
    "🏆 « *Dieu a choisi les choses folles du monde pour confondre les sages.* » — 1 Cor 1:27",
    "💎 « *Car l'Éternel est un soleil et un bouclier ; il donne la grâce et la gloire.* » — Ps 84:12",
    "🎁 « *Toute bonne chose donnée, tout don parfait, descend d'en haut.* » — Jac 1:17",
    "🌅 « *Sa miséricorde se renouvelle chaque matin ; grande est ta fidélité !* » — Lam 3:23",
    "🦅 « *Ceux qui espèrent en l'Éternel renouvellent leur force. Ils montent avec des ailes comme des aigles.* » — És 40:31",
    "🙏 « *Je vous donnerai ce que votre cœur désire, si vous vous délectez en l'Éternel.* » — Ps 37:4",
    "💡 « *La lumière brille dans les ténèbres et les ténèbres ne l'ont pas reçue, mais toi tu l'as reçue !* » — Jn 1:5",
    "🎶 « *C'est l'Éternel qui agit : c'est admirable à nos yeux !* » — Ps 118:23",
    "🌺 « *Le Seigneur m'a répondu le jour où je l'ai appelé, Il a augmenté mes forces.* » — Ps 138:3",
    "⭐ « *Je t'ai choisi et je ne t'ai pas rejeté. Je suis avec toi.* » — És 41:9-10",
    "🏅 « *Dieu a renversé les puissants de leur trône et Il a élevé les humbles.* » — Luc 1:52",
    "🎊 « *L'Éternel est ma lumière et mon salut — de qui aurais-je peur ?* » — Ps 27:1",
    "🌻 « *Sa grâce m'a suffi car sa puissance s'accomplit dans la faiblesse.* » — 2 Cor 12:9",
    "🔑 « *Ce que l'Éternel ouvre, personne ne peut fermer. Sa faveur était sur toi.* » — Apo 3:7",
    "🌊 « *Il a commandé et la tempête s'est calmée. Ses vagues ont été apaisées.* » — Ps 107:29",
    "🌠 « *La victoire appartient à l'Éternel. Il te l'a accordée sans combat.* » — Prov 21:31",
    "🎯 « *Tout ce que je fais réussit car l'Éternel dirige mes pas.* » — Ps 1:3",
    "🔆 « *Je suis venu pour que vous ayez la vie, et que vous l'ayez en abondance.* » — Jn 10:10",
    "🌟 « *Dieu fait bien toutes choses. Il t'a accordé la victoire au premier instant.* » — Marc 7:37",
    "💫 « *Cherchez premièrement le royaume de Dieu, et tout le reste vous sera donné.* » — Matt 6:33",
    "🎉 « *Tu as transformé mon deuil en allégresse, tu as enlevé mon sac et tu m'as ceint de joie.* » — Ps 30:12",
    "🙌 « *L'Éternel combat pour toi ; toi, sois tranquille.* » — Ex 14:14",
    "🌈 « *Dieu t'a fait triompher sans que tu transpires. Sa grâce directe est ta portion.* » — 2 Cor 2:14",
    "⚡ « *Voici, je fais toutes choses nouvelles. Ce que J'ai promis, Je l'accomplis sur-le-champ.* » — Apo 21:5",
    "💪 « *Ne t'effraye pas car Je suis ton Dieu ; Je t'ai affermi, Je t'ai aidé.* » — És 41:10",
    "🏆 « *Dieu nous donne la victoire par notre Seigneur Jésus-Christ.* » — 1 Cor 15:57",
    "🌺 « *Tu as été fidèle, entre dans la joie de ton Seigneur.* » — Matt 25:21",
    "🎁 « *Toute grâce est l'œuvre de Dieu seul. Il t'a couronné ce soir.* » — Ps 103:4",
    "🔥 « *Je me rappellerai les hauts faits de l'Éternel ; oui, je me souviendrai de tes miracles d'autrefois.* » — Ps 77:12",
    "🌅 « *C'est lui qui donne la force d'acquérir des richesses, pour confirmer son alliance.* » — Deut 8:18",
    "✨ « *Pour toi qui crains mon nom, se lèvera le soleil de la justice avec la guérison dans ses rayons.* » — Mal 4:2",
    "🦅 « *Je suis avec toi pour te délivrer, dit l'Éternel.* » — Jér 1:19",
    "🎶 « *Béni soit l'Éternel qui ne nous a pas livrés en proie à leurs dents !* » — Ps 124:6",
    "💎 « *Tu ouvres ta main, et tu rassasies à souhait tout ce qui a vie.* » — Ps 145:16",
    "🌻 « *Car c'est moi qui connais les projets que j'ai formés sur vous, projets de paix et non de malheur.* » — Jér 29:11",
    "🌠 « *L'Éternel accomplit son œuvre — admire ce qu'Il a fait pour toi directement.* » — Ps 111:2",
    "🎊 « *Dieu t'a exaucé avant la fin de ta prière. C'est sa manière d'agir.* » — Dan 9:23",
    "🌊 « *Il a répondu à ma prière et m'a accordé ma demande.* » — Ps 20:5",
    "🔑 « *Heureux l'homme qui met sa confiance en l'Éternel.* » — Ps 34:9",
    "🎯 « *Tout ce que vous demanderez en mon nom, je le ferai.* » — Jn 14:13",
    "💡 « *Dieu a dit oui, et sur-le-champ sa parole s'est accomplie.* » — 2 Cor 1:20",
    "⭐ « *L'Éternel est bon pour ceux qui espèrent en lui. Sa grâce est venue ce soir.* » — Lam 3:25",
    "🏅 « *La bénédiction de l'Éternel enrichit, et il n'y joint aucune peine.* » — Prov 10:22",
    "🙌 « *Je ne te laisserai point et je ne t'abandonnerai point.* » — Jos 1:5",
    "🎵 « *Dieu a mis dans ma bouche un chant nouveau. Sa grâce directe est mon cantique !* » — Ps 40:4",
    "🌟 « *Sa droite et son bras saint lui ont donné la victoire.* » — Ps 98:1",
    "🏆 « *Il n'y a pas eu de peine, il n'y a eu que la grâce — et c'est Dieu.* » — Ps 118:16",
    "🌺 « *Je savais que tu m'exauces toujours.* » — Jn 11:42",
    "💫 « *Par la foi tu as vu la victoire. Dieu honore la foi immédiate.* » — Héb 11:1",
    "🔆 « *Tu as frappé à la porte et immédiatement elle s'est ouverte.* » — Matt 7:8",
    "🎉 « *Le Seigneur a accompli pour toi de grandes choses.* » — Ps 126:3",
    "🌈 « *J'ai demandé, j'ai cherché, j'ai frappé — et la réponse fut immédiate.* » — Matt 7:7",
    "⚡ « *Il n'est pas lent à accomplir ses promesses. Il était déjà prêt.* » — 2 Pi 3:9",
    "💪 « *Le Seigneur est proche de tous ceux qui l'invoquent avec sincérité.* » — Ps 145:18",
    "🌻 « *C'est l'Éternel qui a fait cela — et c'est admirable à nos yeux.* » — Ps 118:23",
    "🎵 « *Il a mis un chant nouveau dans ma bouche — un chant de louange à notre Dieu.* » — Ps 40:3",
    "🌿 « *Goûtez et voyez combien l'Éternel est bon. Heureux l'homme qui se confie en lui !* » — Ps 34:9",
    "🏅 « *Je t'aime, Éternel, ma force ! L'Éternel est mon rocher, ma forteresse.* » — Ps 18:2",
    "🌟 « *L'Éternel a accompli mon désir. L'Éternel exaucera ma supplication.* » — Ps 6:10",
    "🎯 « *Dieu est pour nous un Dieu qui sauve ; l'Éternel a des issues pour échapper à la mort.* » — Ps 68:21",
    "🔥 « *Invoke-moi et je te répondrai. Je t'ai répondu ce soir !* » — Jér 33:3",
    "🌊 « *J'ai crié à l'Éternel dans ma détresse et il m'a exaucé.* » — Jon 2:3",
    "✨ « *L'Éternel a fait éclater sa délivrance ; il a révélé sa justice aux yeux des nations.* » — Ps 98:2",
    "🏆 « *Mon cœur exulte en l'Éternel, ma force s'élève grâce à l'Éternel.* » — 1 Sam 2:1",
    "💫 « *Tu es mon secours et mon libérateur ; Éternel, mon Dieu, ne tarde pas !* » — Ps 40:18",
    "🌈 « *Dieu a dit : je comblerai toutes tes demandes selon ses richesses en gloire.* » — Phil 4:19",
    "⭐ « *Voici, je suis l'Éternel, le Dieu de toute chair. Y a-t-il rien de trop merveilleux pour moi ?* » — Jér 32:27",
    "🎁 « *Tu as accordé la demande de ses lèvres et l'aspiration de son cœur.* » — Ps 21:3",
    "💡 « *Tu as exaucé ma prière, car tu es fidèle et juste pour pardonner.* » — 1 Jn 1:9",
    "🌺 « *L'Éternel te bénisse et te garde ! L'Éternel fasse luire sa face sur toi et t'accorde sa grâce !* » — Nomb 6:24-25",
    "🦅 « *Il satisfait d'autant de biens ton désir que tu te renouvelles comme l'aigle.* » — Ps 103:5",
    "🎶 « *Dieu a exaucé ma voix et mon appel ; il a prêté l'oreille à ma prière.* » — Ps 66:19",
    "🌻 « *La main de l'Éternel n'est pas trop courte pour sauver, ni son oreille trop dure pour entendre.* » — És 59:1",
    "🙌 « *Il n'a point méprisé ni dédaigné la détresse du pauvre ; il n'a point caché sa face, mais il l'a exaucé.* » — Ps 22:25",
    "💎 « *Je t'aime tendrement, Éternel, car tu as entendu ma supplication.* » — Ps 116:1",
    "🔑 « *Tu m'as répondu le jour où je t'ai invoqué, tu m'as fortifié par ta force.* » — Ps 138:3",
    "🌅 « *L'Éternel a entendu ma supplication ; l'Éternel a reçu ma prière.* » — Ps 6:10",
    "⚡ « *C'est lui qui exauce la prière ; c'est pourquoi tout être humain s'adresse à lui.* » — Ps 65:3",
    "🎊 « *Gloire à celui qui peut faire, par la puissance qui agit en nous, infiniment au-delà de tout ce que nous demandons.* » — Éph 3:20",
    "🌠 « *Si vous demeurez en moi et que mes paroles demeurent en vous, demandez ce que vous voudrez et cela vous sera accordé.* » — Jn 15:7",
    "🎉 « *Jusqu'à présent vous n'avez rien demandé en mon nom. Demandez, et vous recevrez, afin que votre joie soit complète.* » — Jn 16:24",
    "💪 « *L'Éternel ne refuse pas sa grâce à ceux qui marchent dans l'intégrité.* » — Ps 84:12",
    "🏅 « *Que ta grâce soit sur nous selon notre espérance en toi.* » — Ps 33:22",
    "🎯 « *Dieu a fait éclater sa bonté d'une façon merveilleuse et m'a sauvé.* » — Ps 31:22",
    "🌟 « *Le salut des justes vient de l'Éternel ; il est leur appui au temps de la détresse.* » — Ps 37:39",
    "🌿 « *Tu as été pour moi un refuge, une tour forte en face de l'ennemi.* » — Ps 61:4",
    "🎵 « *Il t'a couronné de grâce et de miséricorde ; je chanterai à l'Éternel car il m'a rendu du bien.* » — Ps 13:6",
    "🌸 « *L'Éternel ton Dieu est au milieu de toi, comme un héros qui sauve. Il fera de toi sa plus grande joie.* » — Soph 3:17",
    "🕊️ « *Sa miséricorde subsiste à jamais sur ceux qui le craignent, et sa justice envers les enfants de ses enfants.* » — Ps 103:17",
    "🌼 « *L'amour de Dieu est répandu dans nos cœurs par le Saint-Esprit qui nous a été donné — et tu l'as senti ce soir !* » — Rom 5:5",
    "🌱 « *Dieu a scellé ta victoire dans ses plans depuis l'éternité. Ce soir, Il t'a simplement révélé son plan.* » — Éph 1:11",
    "💙 « *Tu n'as pas choisi Dieu, c'est lui qui t'a choisi et établi pour que tu portes du fruit.* » — Jn 15:16",
    "🌤️ « *Que ta droite me sauve ! L'Éternel accomplira son œuvre pour moi.* » — Ps 138:8",
    "🎀 « *Il a exaucé la prière des indigents et n'a pas méprisé leur supplication.* » — Ps 102:18",
    "☀️ « *Mon aide vient de l'Éternel qui a fait les cieux et la terre.* » — Ps 121:2",
    "🌞 « *Puisse l'Éternel t'accorder ce que tu désires et réaliser tous tes projets !* » — Ps 20:5",
    "💥 « *Tu m'as répondu en m'accordant une grande délivrance. Je crie vers l'Éternel et il répond.* » — Ps 18:51",
    "🎖️ « *Dieu est mon secours et celui qui soutient mon âme.* » — Ps 54:6",
    "🌟 « *Ne t'ai-je pas commandé ? Sois fort et courageux ! Car l'Éternel t'a donné la victoire.* » — Jos 1:9",
    "🌻 « *L'amour de l'Éternel dure à jamais pour ceux qui le craignent. Sa grâce est ta victoire ce soir.* » — Ps 103:17",
    "🔮 « *Mon rocher et mon libérateur, tu m'as placé dans un lieu élevé.* » — Ps 18:49",
    "🎇 « *Je proclamerai les louanges de l'Éternel selon toute sa justice ; je chanterai l'Éternel qui m'a accordé la victoire.* » — Ps 7:18",
    "🌹 « *L'Éternel est grand et très digne de louange dans la ville de notre Dieu.* » — Ps 48:2",
    "💐 « *Heureux le peuple dont l'Éternel est le Dieu ! Sa victoire est ton témoignage.* » — Ps 144:15",
    "🎗️ « *Le Seigneur est juste en toutes ses voies, et plein d'amour en toutes ses œuvres.* » — Ps 145:17",
    "🕊️ « *L'Éternel te bénira abondamment dans tout le travail de tes mains.* » — Deut 15:10",
    "⛅ « *La bénédiction de l'Éternel est sur vous ! Nous vous bénissons au nom de l'Éternel.* » — Ps 129:8",
    "🌅 « *C'est lui qui te donne la force et la puissance — et tu l'as vu ce soir !* » — Deut 8:18",
    "🎆 « *L'Éternel a révélé son bras saint aux yeux de toutes les nations. Tu as vu sa puissance.* » — És 52:10",
    "🌊 « *Dieu a parlé dans sa sainteté — et je suis dans la joie.* » — Ps 108:8",
    "🏵️ « *Loue l'Éternel, car il est bon et sa grâce dure à jamais. Il t'a favorisé ce soir.* » — Ps 118:1",
    "🌺 « *L'Éternel est ta garde, l'Éternel est ton ombre à ta main droite.* » — Ps 121:5",
    "✨ « *La victoire m'appartient en Christ Jésus, car je suis plus que vainqueur par celui qui m'a aimé.* » — Rom 8:37",
    "🔥 « *L'Éternel combat pour moi — et je suis victorieux ce soir !* » — Ex 14:14",
    "🎯 « *À toi qui peux faire infiniment au-delà de tout ce qu'on demande, soit la gloire à jamais !* » — Éph 3:20-21",
    "💫 « *Tu m'as accordé la victoire sans même que je la mérite — c'est la grâce pure.* » — 2 Tim 1:9",
    "🌟 « *Par Dieu nous ferons des exploits, car c'est lui qui foulera aux pieds nos ennemis.* » — Ps 60:14",
    "🌼 « *Aujourd'hui l'Éternel a dit oui à ma demande. Sa parole ne retourne jamais à lui sans avoir prospéré.* » — És 55:11",
    "🎊 « *Il exauce le désir de ceux qui le craignent, il entend leurs cris et les sauve.* » — Ps 145:19",
    "🌙 « *Que l'Éternel réponde dans le temps de la détresse, que le nom du Dieu de Jacob te mette à l'abri !* » — Ps 20:2",
    "⚡ « *Regarde, l'Éternel t'a accordé ce pays. Monte et saisis-le !* » — Deut 1:21",
    "💎 « *L'Éternel a écouté la voix de mes supplications quand j'ai crié à lui.* » — Ps 28:6",
    "🌈 « *Ce soir, la grâce de Dieu t'a précédé. Il avait préparé ta victoire avant que tu demandes.* » — Éph 2:10",
    "🏆 « *Par toi, nous renversons nos adversaires. Par ton nom, nous foulons aux pieds ceux qui se soulèvent contre nous.* » — Ps 44:6",
    "🌷 « *Il a répondu à ma prière et ma bouche est pleine de louanges.* » — Ps 71:8",
    "💪 « *Tu m'as accordé la grâce au bon moment. Ta grâce directe est ma portion.* » — Héb 4:16",
    "🎁 « *Dieu t'a prouvé ce soir qu'il est l'Éternel qui pourvoit.* » — Gen 22:14",
    "🙏 « *C'est l'Éternel qui triomphe. Gloire à lui pour toujours et à jamais !* » — Ex 15:18",
    "🌿 « *Puisse la gloire de l'Éternel durer à jamais ! Que l'Éternel se réjouisse en ses œuvres !* » — Ps 104:31",
    "🌞 « *Il m'a délivré parce qu'il m'aimait. Sa grâce directe n'avait pas de prix.* » — Ps 18:20",
    "🎵 « *Je chanterai à l'Éternel un cantique nouveau. Il a fait des choses admirables.* » — Ps 98:1",
]

# ═══════════════════════════════════════════════════════════════════
#  ✅1️⃣  GAGNÉ R1 — Victoire après une première persévérance
# ═══════════════════════════════════════════════════════════════════
PAROLES_GAGNE_R1 = [
    "💪 « *Sois fort et courageux ! N'aie pas peur car l'Éternel ton Dieu est avec toi.* » — Jos 1:9",
    "🔥 « *Nous savons que la tribulation produit la persévérance.* » — Rom 5:3",
    "🌟 « *Heureux l'homme qui supporte patiemment la tentation car il recevra la couronne de vie.* » — Jac 1:12",
    "🏆 « *Celui qui persévère jusqu'à la fin sera sauvé.* » — Matt 24:13",
    "⭐ « *Continuez, ne vous relâchez pas, car votre travail aura sa récompense.* » — 2 Chr 15:7",
    "🌈 « *Ne te laisse pas vaincre par le mal, mais surmonte le mal par le bien.* » — Rom 12:21",
    "🎯 « *Tu es tombé une fois, mais tu t'es relevé — et c'est là que Dieu t'a récompensé !* » — Prov 24:16",
    "💡 « *La persévérance forme le caractère, et le caractère l'espérance.* » — Rom 5:4",
    "🌺 « *À celui qui vaincra, je donnerai à manger de l'arbre de vie.* » — Apo 2:7",
    "🦅 « *Il bande mes pieds comme ceux des biches et me fait marcher sur mes lieux élevés.* » — Ps 18:34",
    "🌅 « *L'affliction du juste est grande, mais l'Éternel le délivre de toutes.* » — Ps 34:20",
    "💎 « *Ce qui est né de Dieu vainc le monde ; et la victoire qui a vaincu le monde, c'est notre foi.* » — 1 Jn 5:4",
    "🎁 « *Je suis persuadé que celui qui a commencé en toi cette bonne œuvre la rendra parfaite.* » — Phil 1:6",
    "🌊 « *Il a dit non en première instance, mais la foi a insisté et Dieu a cédé à ta confiance.* » — Luc 18:7",
    "🔑 « *Frappez et l'on vous ouvrira. La deuxième frappe a tout changé !* » — Matt 7:7",
    "✨ « *L'Éternel ton Dieu est au milieu de toi, un héros qui sauve. Il s'est réjoui de toi.* » — Soph 3:17",
    "🎶 « *Je te bénirai et tu seras une bénédiction. Tiens bon.* » — Gen 12:2",
    "🌻 « *La joie de l'Éternel est votre force — même après un premier refus.* » — Néh 8:10",
    "🏅 « *L'Éternel est fidèle ; il vous affermira et vous gardera du mal.* » — 2 Thes 3:3",
    "🙌 « *Revêtez-vous de toutes les armes de Dieu. Tenez ferme — la victoire arrive !* » — Éph 6:13",
    "🔆 « *Dieu ne tarde pas à accomplir ce qu'il a promis. Il t'a rendu justice.* » — Luc 18:8",
    "🌠 « *Je sais que l'Éternel m'accordera la victoire. Sa parole ne peut manquer.* » — Ps 20:7",
    "⚡ « *Ne vous découragez pas : au moment fixé, la moisson viendra — et elle est venue !* » — Gal 6:9",
    "💪 « *Tu as lutté avec Dieu et avec les hommes, et tu as été vainqueur.* » — Gen 32:28",
    "🎉 « *Il n'a pas méprisé ni rejeté la souffrance du malheureux ; Il a entendu.* » — Ps 22:25",
    "🌟 « *L'espérance ne confond point, car l'amour de Dieu est répandu dans nos cœurs.* » — Rom 5:5",
    "🎊 « *Ne crains pas, car je t'ai racheté, je t'ai appelé par ton nom : tu es à moi.* » — És 43:1",
    "🔥 « *Ta foi t'a sauvé. Va en paix. Le premier pas de persévérance t'a tout apporté.* » — Luc 7:50",
    "🌺 « *À celui qui vaincra je donnerai de la manne cachée.* » — Apo 2:17",
    "💡 « *Ne pleure pas, car le lion de la tribu de Juda a vaincu — et tu es avec lui.* » — Apo 5:5",
    "🎯 « *Soyez fermes, inébranlables, toujours abondants dans l'œuvre du Seigneur.* » — 1 Cor 15:58",
    "🌈 « *Tu as passé par le premier test. Dieu t'a vu tenir — et Il t'a accordé la récompense.* » — Ps 11:5",
    "🦅 « *Après la première attente, la délivrance est venue. Loue l'Éternel !* » — Ps 31:8",
    "🌅 « *Ta lumière se lèvera dans les ténèbres et l'obscurité sera comme le midi.* » — És 58:10",
    "⭐ « *Le Seigneur ramènera les captifs de son peuple. Jacob se réjouira, Israël sera dans l'allégresse.* » — Ps 53:7",
    "💎 « *Dieu a tenu sa promesse après la première épreuve. Sa fidélité est grande.* » — Lam 3:23",
    "🏆 « *Voici, j'ai mis devant toi une porte ouverte que personne ne peut fermer.* » — Apo 3:8",
    "🎁 « *Reviens à moi et je reviendrai à toi, dit l'Éternel des armées.* » — Mal 3:7",
    "🌊 « *Tu as cherché et tu as trouvé. Le premier rattrapage t'a ouvert la porte.* » — Matt 7:8",
    "🔑 « *L'Éternel affermit les pas de l'homme dont Il prend plaisir à la voie.* » — Ps 37:23",
    "✨ « *Dieu n'abandonne pas ceux qui le cherchent. Ta persévérance a payé.* » — Ps 9:11",
    "🎶 « *Chantez à l'Éternel un chant nouveau car Il a fait des merveilles.* » — Ps 98:1",
    "🌻 « *Je t'ai fortifié bien que tu ne me connaisses pas. Je veille sur toi.* » — És 45:5",
    "🏅 « *Ce sont les épreuves qui produisent la persévérance, la persévérance la vertu éprouvée.* » — Rom 5:3-4",
    "🙌 « *Au premier combat, tu n'as pas abandonné. C'est pourquoi Dieu t'a récompensé.* » — 2 Tim 4:7",
    "🔆 « *Ne perds pas ta confiance car elle a une grande récompense.* » — Héb 10:35",
    "🌠 « *L'Éternel t'a fait triompher sur tes ennemis.* » — Deut 28:7",
    "⚡ « *La patience accomplit une œuvre parfaite. Tu l'as vue en R1 ce soir.* » — Jac 1:4",
    "💪 « *Je peux tout par celui qui me fortifie. Le R1 en est la preuve.* » — Phil 4:13",
    "🎉 « *Loué soit Dieu qui ne nous a pas laissé pour proie à leurs dents.* » — Ps 124:6",
    "🌟 « *Dieu t'a couronné de bonté et de miséricorde après le premier rattrapage.* » — Ps 103:4",
    "🎊 « *Sa miséricorde est grande envers nous. Loue l'Éternel !* » — Ps 117:2",
    "🔥 « *Le Seigneur est avec les brisés de cœur. Il n'a pas abandonné ta demande.* » — Ps 34:19",
    "🌺 « *La foi déplace les montagnes. Au R1, ta foi a parlé.* » — Matt 17:20",
    "💡 « *Demandez et vous recevrez. Le R1 prouve que Dieu t'a finalement accordé la grâce.* » — Jn 16:24",
    "🎯 « *Persévère dans tes prières — le R1 est ton témoignage ce soir.* » — Col 4:2",
    "🌈 « *Celui qui croit ne sera point confus — tu l'as vu après le premier essai.* » — Rom 10:11",
    "🦅 « *Tiens ferme, ne te relâche pas ! Car ton œuvre sera récompensée.* » — 2 Chr 15:7",
    "🌅 « *Après la pluie, le beau temps. Après le premier refus, la victoire !* » — Job 8:21",
    "⭐ « *Tu te souviens que tu as failli perdre courage, mais tu as tenu — et voilà la victoire !* » — Héb 12:1",
    "💎 « *La couronne de vie est pour ceux qui ont supporté l'épreuve.* » — Jac 1:12",
    "🌊 « *Voici, l'Éternel a prononcé, et il accomplira sa parole. Il tient ce qu'il promet.* » — Nomb 23:19",
    "🎊 « *Celui qui commence une bonne œuvre en toi la rendra parfaite. Ne lâche pas.* » — Phil 1:6",
    "🌼 « *Ta foi t'a sauvé. Va en paix et sois guéri de ta maladie.* » — Marc 5:34",
    "🌟 « *Celui qui endure jusqu'à la fin sera sauvé. Tu as endurée la première épreuve — et tu es sauvé !* » — Matt 10:22",
    "💥 « *Ne sois pas vaincu par le découragement. Au premier refus, tu as tenu bon — et Dieu t'a honoré.* » — Rom 12:21",
    "🌿 « *Tu as semé dans les larmes de la première épreuve — et tu récoltes dans la joie.* » — Ps 126:5",
    "🔥 « *La tentation ne vous a pas saisis qu'humainement ; mais Dieu a pourvu à l'issue. Tu l'as vue en R1 !* » — 1 Cor 10:13",
    "🏆 « *La foi sans les œuvres est morte. Mais ta foi a agi au R1 — et elle a porté ses fruits.* » — Jac 2:17",
    "⚡ « *Comme Abraham a attendu avec patience, il a obtenu ce qui lui était promis. Toi aussi en R1 !* » — Héb 6:15",
    "🌈 « *L'espérance ne confond point. Tu as espéré au R1 — et l'espérance t'a porté à la victoire.* » — Rom 5:5",
    "🎯 « *Résiste au diable et il fuira loin de toi. Tu as résisté au premier doute — et tu as gagné.* » — Jac 4:7",
    "💡 « *Au premier signe de défaite, tu as cherché la face de Dieu — et il s'est levé pour toi.* » — 2 Chr 7:14",
    "🌺 « *Dieu n'oublie pas le travail de ta foi ni la fatigue de ton amour. R1 en est la preuve.* » — Héb 6:10",
    "🦅 « *Il donne de la force à celui qui est fatigué. Au R1, tu as reçu la force nécessaire.* » — És 40:29",
    "🌅 « *Je t'ai vu dans la première tempête — et je suis intervenu. C'est ma nature.* » — Ps 46:2",
    "💎 « *La persévérance produit une foi éprouvée, et la foi éprouvée produit l'espérance — que tu vois en R1.* » — Rom 5:4",
    "🎁 « *Après le premier combat, le butin de la victoire est plus doux. Savoure ta récompense !* » — 1 Sam 30:20",
    "🌊 « *Tu n'as pas abandonné quand le premier effort a échoué. Dieu a vu ta fidélité.* » — Lam 3:22",
    "🔑 « *La porte ne s'est pas ouverte au premier coup, mais à ta deuxième tentative Dieu a dit : entre !* » — Luc 11:8",
    "✨ « *Tu as cherché l'Éternel et il t'a répondu, il t'a délivré de toutes tes frayeurs — en R1 !* » — Ps 34:5",
    "🎶 « *Ma force et mon cantique, c'est l'Éternel. Il est devenu mon salut au moment du R1.* » — Ex 15:2",
    "🌻 « *L'Éternel est un Dieu qui connaît toutes tes actions. Ta persévérance au R1 n'a pas été vaine.* » — 1 Sam 2:3",
    "🏅 « *Garde le cap de l'espérance car celui qui a fait la promesse est fidèle — tu le vois en R1.* » — Héb 10:23",
    "🙌 « *Après la première nuit de larmes, le matin de la joie est arrivé. Loue l'Éternel !* » — Ps 30:6",
    "🔆 « *Sachant que votre persévérance a une récompense — tu l'as vue au R1.* » — Héb 10:36",
    "🌠 « *Tout homme qui espère en lui ne sera pas confus. Tu as espéré au R1 — et tu es honoré.* » — 1 Pi 2:6",
    "⚡ « *La course que tu as commencée avec le premier effort méritait cette victoire.* » — Héb 12:1",
    "💪 « *Après le premier refus de Joseph d'être vendu, Dieu avait un plan. Ton R1 aussi a un plan.* » — Gen 50:20",
    "🎉 « *Tu as frappé une fois — et l'Éternel t'a ouvert. C'est sa manière de récompenser la foi.* » — Matt 7:8",
    "🌟 « *L'Éternel sonde les cœurs. Il a vu ta foi tenir au R1 et il t'a récompensé.* » — 1 Chr 28:9",
    "🎊 « *La patience du pauvre ne sera pas perdue pour toujours. Dieu a vu ton premier effort.* » — Ps 9:19",
    "🔥 « *Après la première tentative de Daniel de prier malgré l'interdiction, Dieu l'a délivré.* » — Dan 6:10-23",
    "🌺 « *La prière d'Ézéchias après le premier choc de la maladie a été exaucée. Comme toi au R1 !* » — 2 Rois 20:5",
    "💡 « *Elise a frappé les eaux une fois et elles se sont divisées. Ta première frappe a ouvert le chemin.* » — 2 Rois 2:14",
    "🎯 « *Si tu n'avais pas tenu au R1, tu n'aurais pas vu la gloire de Dieu. Tu l'as vu !* » — Jn 11:40",
    "🌈 « *Tu as marché sur les eaux une fois comme Pierre — et Jésus t'a soutenu.* » — Matt 14:29",
    "🦅 « *L'oiseau ne renonce pas après le premier envol difficile. Tu n'as pas renoncé — tu as gagné.* » — Ps 91:12",
    "🌅 « *La grâce que tu as reçue au R1 est plus précieuse que l'or car elle a été gagnée avec foi.* » — 1 Pi 1:7",
    "⭐ « *Après le premier combat de Néhémie contre les moqueurs, il a continué — et le mur a été reconstruit.* » — Néh 4:6",
    "💎 « *Même si tu as trébuché au premier effort, tu t'es relevé. L'Éternel a vu cela.* » — Prov 24:16",
    "🏆 « *Comme le serviteur qui a doublé son talent au premier investissement, tu as reçu ta récompense.* » — Matt 25:21",
    "🎁 « *Après la première résistance de Pharaon, Moïse a continué — et la délivrance est venue. Tu l'as vue !* » — Ex 5:22-6:1",
    "🌊 « *L'Éternel a vu ton premier effort et il t'a dit : c'est assez, je prends le relais.* » — 1 Rois 19:5",
    "🔑 « *La foi qui persiste au premier obstacle mérite la récompense divine. Tu mérites la tienne.* » — Héb 11:6",
    "✨ « *Comme Ruth qui n'a pas abandonné au premier obstacle, ta fidélité a été récompensée.* » — Ruth 1:16",
    "🎶 « *Le chant de victoire après le premier combat est plus doux que le miel. Chante !* » — Jug 5:1",
    "🌻 « *Après la première épreuve, tu es sorti plus fort. C'est le travail de Dieu en toi.* » — Rom 5:3",
    "🏅 « *Ézéchias a prié après la première menace d'Assyrie — et l'ange de l'Éternel est intervenu.* » — 2 Rois 19:35",
    "🙌 « *Ce que tu as vécu au R1 sera un témoignage pour d'autres. Gloire à Dieu !* » — Ps 34:3",
    "🔆 « *Dieu t'a dit au R1 : tu n'es pas seul. Je suis avec toi dans chaque combat.* » — Matt 28:20",
    "🌠 « *La victoire au R1 prouve que tu n'as pas lâché quand les autres auraient abandonné.* » — 2 Chr 15:7",
    "⚡ « *Ton premier effort a été semé en foi — et la récolte de victoire t'appartient.* » — Gal 6:9",
    "💪 « *Comme David qui a ramassé cinq pierres mais n'en avait besoin que d'une — ta foi au R1 était suffisante.* » — 1 Sam 17:40",
    "🎉 « *L'Éternel a honoré ta foi immédiatement après la première épreuve. Sa réponse était rapide !* » — És 58:9",
    "🌟 « *Après le premier pas de foi dans la mer Rouge, les eaux se sont divisées. R1 est ta mer Rouge.* » — Ex 14:21",
    "🎊 « *Tu n'as pas douté quand la première prière semblait sans réponse. Et Dieu t'a exaucé.* » — Marc 11:24",
    "🔥 « *Le premier test a révélé ta foi. Le premier rattrapage a révélé la fidélité de Dieu.* » — Ps 11:5",
    "🌺 « *Tu as semé avec larmes au R0, et tu récoltes avec joie au R1. C'est la loi divine.* » — Ps 126:6",
    "💡 « *La première déception t'a conduit à une foi plus profonde — et Dieu a récompensé cette profondeur.* » — 1 Pi 1:7",
    "🎯 « *Dieu ne t'a pas laissé porter seul la première épreuve. Sa présence était là.* » — Matt 28:20",
    "🌈 « *Après le premier échec apparent, Dieu préparait la vraie victoire. Tu l'as reçue au R1 !* » — Rom 8:28",
    "🦅 « *La première résistance t'a appris à voler plus haut. Maintenant tu planes comme l'aigle.* » — És 40:31",
    "🌅 « *Après la première nuit de vigilance en prière, le matin de la victoire est arrivé.* » — Ps 130:6",
    "⭐ « *Dieu t'a testé une fois et tu as passé l'épreuve. Voici ta récompense.* » — Ps 66:10",
    "💎 « *Ton âme s'est accrochée à Dieu au R0. Et Dieu t'a répondu au R1. C'est sa fidélité.* » — Ps 63:9",
    "🏆 « *Il n'abandonne pas ceux qui le cherchent sincèrement. Tu l'as cherché — et il t'a trouvé.* » — Ps 9:11",
    "🎁 « *Après la première demande, la deuxième réponse est venue. C'est Dieu qui frappe à ta porte.* » — Apo 3:20",
    "🌊 « *Le courant du premier combat ne t'a pas emporté car l'Éternel tenait ta main.* » — És 41:13",
    "🔑 « *Après la première nuit avec Lia, Jacob a eu Rachel. Après le R0 difficile, voici ta Rachel !* » — Gen 29:28",
    "✨ « *L'Éternel a renouvelé ta force après le premier combat. Il ne laisse pas ses enfants à court de force.* » — És 40:31",
    "🎶 « *Comme Siméon qui a attendu toute sa vie le Messie et l'a vu — ta première persévérance a vu la victoire.* » — Luc 2:29",
    "🌻 « *Tu as combattu le bon combat au R1. La couronne de justice t'est réservée.* » — 2 Tim 4:7-8",
    "🏅 « *Après le premier obstacle de Job, sa foi a tenu — et Dieu l'a restauré. Tu es restauré !* » — Job 42:10",
    "🙌 « *Ton nom est écrit dans les cieux depuis ta première victoire par la foi.* » — Luc 10:20",
    "🔆 « *La première persévérance t'a rendu plus fort pour les prochains combats. Merci à Dieu !* » — 2 Cor 12:9",
    "🌠 « *L'ange de l'Éternel est arrivé après ta première prière nocturne. Il était là pour toi.* » — Dan 9:23",
    "⚡ « *Après la première marche autour des murs, la confiance montait. Après le R0, ta foi aussi s'est renforcée.* » — Jos 6:13",
    "💪 « *Tu as fait ce qui était en toi — et Dieu a fait ce qu'il est. C'est le partenariat du R1.* » — 2 Chr 20:17",
    "🎉 « *La première victoire de David sur l'ours et le lion lui a préparé Goliath. Ton R1 prépare ta grande victoire.* » — 1 Sam 17:37",
]

# ═══════════════════════════════════════════════════════════════════
#  ✅2️⃣  GAGNÉ R2 — Victoire après deux épreuves
# ═══════════════════════════════════════════════════════════════════
PAROLES_GAGNE_R2 = [
    "💪 « *Combats le bon combat de la foi. Deux fois tu as tenu — et tu as gagné !* » — 1 Tim 6:12",
    "🔥 « *Voici, je t'ai éprouvé dans la fournaise de l'affliction. Et tu es sorti pur !* » — És 48:10",
    "🌟 « *L'Éternel fait grâce à celui qui patiente jusqu'à la troisième occasion.* » — Lam 3:26",
    "🏆 « *Soyez patients, affermissez vos cœurs, car l'avènement du Seigneur est proche.* » — Jac 5:8",
    "⭐ « *Après deux épreuves, Dieu t'a ouvert la porte. C'est Sa signature.* » — Ps 107:13",
    "🌈 « *Si tu passes par les eaux, je serai avec toi. Si tu passes par les rivières, elles ne te submergeront pas.* » — És 43:2",
    "🎯 « *Dieu t'a mis dans la fournaise deux fois, mais tu en es sorti sans odeur de feu !* » — Dan 3:27",
    "💡 « *La patience produit une œuvre parfaite. Deux fois tu as persisté.* » — Jac 1:4",
    "🌺 « *Ne sois pas vaincu par le mal. Deux fois le mal t'a frappé, mais tu l'as surmonté.* » — Rom 12:21",
    "🦅 « *Deux fois la tempête, mais Dieu était dans la barque. La paix est venue.* » — Marc 4:39",
    "🌅 « *Deux fois le refus, mais la troisième fois l'Éternel t'a parlé.* » — 1 Sam 3:8",
    "💎 « *Ta foi a été éprouvée deux fois et elle a tenu. Elle vaut plus que l'or.* » — 1 Pi 1:7",
    "🎁 « *L'argent éprouvé au creuset — ta foi a passé deux fois l'épreuve.* » — Ps 12:7",
    "🌊 « *La vague a frappé deux fois, mais le rocher a tenu. Tu es ce rocher.* » — Matt 7:25",
    "🔑 « *Deux fois l'obscurité, mais la lumière est venue. Gloire à Dieu !* » — Jn 1:5",
    "✨ « *Ne te décourage pas. L'Éternel ta fortifié deux fois pour te conduire à la victoire.* » — És 41:10",
    "🎶 « *Je t'ai éprouvé comme on éprouve l'argent. Deux fois au feu — tu es pur !* » — Zach 13:9",
    "🌻 « *Il a dit : cherche ma face. J'ai cherché deux fois et Il m'a répondu.* » — Ps 27:8",
    "🏅 « *Après deux longues nuits, le matin de la joie est venu.* » — Ps 30:6",
    "🙌 « *Deux fois Pierre a nié, mais Jésus ne l'a pas abandonné. Dieu ne t'abandonne pas non plus.* » — Luc 22:61-62",
    "🔆 « *Béni soit l'Éternel qui renouvelle ta force après chaque épreuve.* » — És 40:29",
    "🌠 « *Après deux combats, la victoire est d'autant plus douce. Goûte-la !* » — Ps 34:9",
    "⚡ « *Deux fois l'obscurité, mais Dieu avait tout calculé pour ta gloire.* » — Rom 8:28",
    "💪 « *Job a perdu deux fois, mais Dieu lui a tout rendu au double. Ta victoire vaut double !* » — Job 42:10",
    "🎉 « *L'Éternel m'a répondu après la deuxième prière. Sa grâce ne faillit jamais.* » — Ps 118:5",
    "🌟 « *Deux fois le chemin fut barré, mais Dieu a ouvert un autre passage.* » — És 43:19",
    "🎊 « *Deux fois dans la tempête avec Paul, mais Dieu avait dit : aucun ne périra.* » — Ac 27:24",
    "🔥 « *Tu as traversé deux rivières. L'Éternel était avec toi à chaque pas.* » — Jos 3:17",
    "🌺 « *Même quand la vigne ne fleurit pas deux fois, je me réjouirai en l'Éternel.* » — Hab 3:17-18",
    "💡 « *Deux fois dans l'obscurité mais tu n'as pas lâché ta foi — et Dieu t'a honoré.* » — Héb 11:6",
    "🎯 « *Dieu a permis deux épreuves pour montrer Sa gloire dans ta victoire finale.* » — Jn 11:4",
    "🌈 « *Deux fois l'enfant de Sunam mourut, mais Élisée pria deux fois et il ressuscita.* » — 2 Rois 4:35",
    "🦅 « *Deux fois dans l'arène, mais le lion a été fermé. Tu sors vivant !* » — Dan 6:23",
    "🌅 « *Après la deuxième nuit, l'ange t'a touché et t'a dit : lève-toi et mange.* » — 1 Rois 19:7",
    "⭐ « *Deux fois Gédéon a demandé un signe, et deux fois Dieu a répondu. Ta foi est confirmée.* » — Jug 6:39",
    "💎 « *Éprouvé deux fois au feu, tu en es sorti victorieux. Tu es de l'or pur !* » — Job 23:10",
    "🏆 « *Deux fois dans la vallée de l'ombre, mais l'Éternel était là.* » — Ps 23:4",
    "🎁 « *Après deux tentatives, David a frappé Goliath. Ta confiance a vaincu.* » — 1 Sam 17:49",
    "🌊 « *Deux fois les mers se sont levées, mais Dieu t'a conduit sain et sauf.* » — Ex 14:22",
    "🔑 « *Deux fois dans le puits comme Joseph, mais la délivrance est venue.* » — Gen 37:24",
    "✨ « *Ta patience de deux cycles t'a valu la couronne. Bénis l'Éternel !* » — Jac 1:12",
    "🎶 « *Deux fois au bord du gouffre, mais l'Éternel a tenu ta main.* » — Ps 73:23",
    "🌻 « *Deux épreuves pour une seule victoire — le plan de Dieu est parfait.* » — Jér 29:11",
    "🏅 « *Ne perds pas courage car tu as tenu deux fois. Quelle foi !* » — Héb 10:36",
    "🙌 « *Deux fois la croix s'est alourdie, mais tu n'as pas abandonné. Tu mérites la victoire.* » — Luc 9:23",
    "🔆 « *Deux fois Pierre a marché sur l'eau, une fois il a coulé — mais Jésus l'a saisi. Il t'a saisi aussi.* » — Matt 14:31",
    "🌠 « *Dieu a dit deux fois à Élie : lève-toi. Et toi aussi, tu t'es levé.* » — 1 Rois 19:7",
    "⚡ « *Deux fois dans la fournaise, mais le quatrième homme était là. Dieu était avec toi.* » — Dan 3:25",
    "💪 « *Deux fois tombé, deux fois relevé. C'est cela la foi victorieuse.* » — Prov 24:16",
    "🎉 « *Après deux épreuves, la joie est encore plus grande. Savoure ta victoire.* » — Ps 126:5",
    "🌟 « *Deux fois dans l'obscurité mais tu as toujours vu la lumière au bout.* » — Jn 8:12",
    "🎊 « *Ta patience de deux rondes est un témoignage pour tous ceux qui t'entourent.* » — Héb 12:1",
    "🔥 « *Deux fois l'ennemi t'a attaqué, deux fois Dieu t'a défendu.* » — Ps 34:8",
    "🌺 « *Deux fois le doute a frappé, mais ta foi a résisté. Dieu t'honore.* » — Matt 21:22",
    "💡 « *Deux fois dans la nuit de Gethsémani, mais la résurrection vient toujours le matin.* » — Ps 30:6",
    "🎯 « *La persévérance de deux rondes te vaut aujourd'hui une récompense double.* » — Job 42:10",
    "🌈 « *Dieu a attendu ta deuxième tentative pour intervenir et montrer sa gloire.* » — Jn 11:6",
    "🦅 « *Deux fois dans la vallée, mais tu n'as pas abandonné. Dieu t'a vu.* » — Ps 18:3",
    "🌅 « *Après le deuxième refus de Pharaon, la délivrance d'Israël était imminente.* » — Ex 8:1",
    "⭐ « *Deux fois tu as frappé à la porte, et au deuxième coup Dieu a dit : entre !* » — Matt 7:8",
    "💎 « *Deux épreuves, une victoire. C'est la méthode de Dieu.* » — 1 Cor 10:13",
    "🌸 « *Après deux essais, Dieu a ouvert une porte qu'aucun homme ne peut fermer.* » — Apo 3:7",
    "🎯 « *Deux fois tu as tendu la main vers Lui, et deux fois Il t'a tendu la sienne.* » — Ps 138:7",
    "🕊️ « *La double épreuve produit une double gloire. C'est le calcul du ciel.* » — 2 Cor 4:17",
    "🌟 « *Deux fois Abraham a levé le couteau de l'obéissance — et Dieu a dit : maintenant je sais que tu m'aimes.* » — Gen 22:12",
    "🔥 « *Deux fois dans le desert et deux fois Dieu a fourni de l'eau. Tu ne manques de rien.* » — Ex 17:6",
    "💪 « *Deux fois Noé a envoyé la colombe — et la deuxième fois, elle est revenue avec un rameau. Ta victoire est ton rameau !* » — Gen 8:11",
    "🌈 « *Deux fois dans la fournaise d'Abraham — mais Dieu l'en a sorti. Tu sors aussi avec Lui.* » — Gen 15:17",
    "🎯 « *Deux fois Jacob a lutté — contre Esaü et avec Dieu — et les deux fois il a été victorieux.* » — Gen 32:28",
    "💡 « *Deux fois dans la prison avec Joseph — mais chaque fois Dieu préparait quelque chose de plus grand.* » — Gen 41:1",
    "🌺 « *Deux fois l'armée de Pharaon a menacé — mais deux fois Dieu a séparé les eaux.* » — Ex 14:16",
    "🦅 « *Deux fois dans le désert avec Élie — et deux fois l'ange l'a touché et nourri.* » — 1 Rois 19:7",
    "🌅 « *Deux fois dans la gueule du lion avec Daniel — mais deux fois Dieu a fermé la gueule du lion.* » — Dan 6:22",
    "💎 « *Deux fois sous la menace de mort avec Esther — mais deux fois le roi a tendu son sceptre.* » — Est 5:2",
    "🎁 « *Deux fois dans le ventre de l'affliction avec Jonas — et deux fois Dieu a recraché la délivrance.* » — Jon 2:11",
    "🌊 « *Deux fois dans l'impasse avec les apôtres — et deux fois Dieu a ouvert les portes de la prison.* » — Ac 16:26",
    "🔑 « *Deux fois Pierre a dormi entre deux soldats — mais l'ange l'a libéré. Tu es libéré.* » — Ac 12:7",
    "✨ « *Deux fois dans le feu de la tribulation — et deux fois l'Éternel t'a dit : c'est moi, n'aie pas peur.* » — Matt 14:27",
    "🎶 « *Deux fois dans la vallée obscure avec le Psalmiste — et deux fois l'Éternel était son berger.* » — Ps 23:4",
    "🌻 « *Deux fois face à Goliath — et deux fois la pierre de la foi a atteint sa cible.* » — 1 Sam 17:50",
    "🏅 « *Deux fois au bord du lac sans poissons — et deux fois Jésus a dit : jette le filet à droite.* » — Jn 21:6",
    "🙌 « *Deux fois dans la maladie avec Naaman — et deux fois l'Éternel avait la guérison prête.* » — 2 Rois 5:14",
    "🔆 « *Deux fois l'adversité de Rut — et deux fois la fidélité a porté ses fruits avec Boaz.* » — Ruth 4:13",
    "🌠 « *Deux fois la résistance de Néhémie — et deux fois le mur a avancé malgré les ennemis.* » — Néh 6:15",
    "⚡ « *Deux fois face aux flammes avec Shadrach — et deux fois le quatrième homme était dans la fournaise.* » — Dan 3:25",
    "💪 « *Deux fois dans le puits de la trahison — et deux fois la main de Dieu t'a sorti.* » — Gen 37:28",
    "🎉 « *Deux fois dans l'angoisse de David devant Saül — et deux fois Dieu a été son rocher.* » — 1 Sam 24:1-10",
    "🌟 « *Deux fois sous la menace des nations — et deux fois l'Éternel a combattu pour son peuple.* » — 2 Chr 20:15",
    "🎊 « *Deux fois dans le creux de la vague — et deux fois Dieu a marché sur les eaux vers toi.* » — Matt 14:25",
    "🔥 « *Deux fois dans le creuset — et les deux fois tu es sorti pur comme l'or.* » — Mal 3:3",
    "🌺 « *Deux fois les portes de la mort se sont ouvertes — et deux fois Dieu t'a rappelé à la vie.* » — Ps 68:21",
    "💡 « *Deux fois la femme Sunamite a pleuré — et deux fois Élisée a prié et Dieu a répondu.* » — 2 Rois 4:36",
    "🎯 « *Deux fois Josué a cru à l'impossible — et deux fois l'impossible est devenu possible.* » — Jos 10:12-13",
    "🌈 « *Deux fois dans le joug de l'esclavage avec Israël — et deux fois Dieu a dit : je suis l'Éternel qui libère.* » — Lév 26:13",
    "🦅 « *Deux fois Abraham a dû quitter sa terre — et deux fois Dieu lui a dit : je serai avec toi.* » — Gen 12:1",
    "🌅 « *Deux fois dans le sein du doute comme Thomas — et deux fois Jésus est apparu pour confirmer sa résurrection.* » — Jn 20:27",
    "⭐ « *Deux fois dans la nuit de Gethsémani — mais le calice de la victoire t'a été remis.* » — Matt 26:39-44",
    "💎 « *Deux fois la promesse de Dieu à Abraham a semblé impossible — et deux fois elle s'est accomplie.* » — Gen 21:2",
    "🏆 « *Deux épreuves méritent une double couronne. Tu as la tienne !* » — 2 Tim 4:8",
    "🎁 « *Dieu a restauré Job au double après deux séries d'épreuves. Ta restauration est double !* » — Job 42:10",
    "🌊 « *Deux fois dans l'obscurité de la foi — et deux fois la lumière de Dieu a brillé encore plus fort.* » — Ps 119:105",
    "🔑 « *Deux fois Dieu a semblé en retard — et deux fois il a prouvé qu'il est exactement à l'heure.* » — Jn 11:21-25",
    "✨ « *Deux fois dans le silence de Dieu — et deux fois la réponse est venue au bon moment.* » — Ps 46:11",
    "🎶 « *Deux fois le peuple a douté dans le désert — et deux fois Dieu a fourni la manne.* » — Ex 16:35",
    "🌻 « *Deux fois dans les ténèbres de Gethsémani — mais la résurrection au R2 vaut plus que l'entrée triomphale.* » — Jn 20:1",
    "🏅 « *Deux fois sous la croix — et deux fois Dieu a dit : relève-toi et marche.* » — Luc 7:14",
    "🙌 « *Deux fois la flamme a semblé s'éteindre — mais l'huile de la grâce de Dieu a alimenté le feu.* » — Zach 4:6",
    "🔆 « *Deux fois la semence est tombée sur un sol difficile — mais au R2, elle a trouvé la bonne terre.* » — Matt 13:8",
    "🌠 « *Deux fois en mer avec Paul — et deux fois l'ange de Dieu a dit : n'aie pas peur.* » — Ac 27:23",
    "⚡ « *Deux fois les murailles ont menacé de tomber — et deux fois Dieu t'a protégé.* » — Néh 4:17",
    "💪 « *Deux fois la peur a frappé ton cœur — et deux fois Dieu a dit : je suis le Dieu qui pourvoit.* » — Gen 22:14",
    "🎉 « *La double épreuve n'a pas eu raison de ta foi. Gloire à Dieu pour cela !* » — 1 Cor 15:57",
    "🌟 « *Deux fois dans la fosse aux lions — mais les anges ont fermé les gueules et tu es sorti.* » — Dan 6:22",
    "🎊 « *Deux fois la tentation de renoncer — et deux fois ta foi a dit : non, je continue avec Dieu.* » — Jos 24:15",
    "🔥 « *Deux fois Josaphat a été entouré d'ennemis — et deux fois les chantres en tête ont remporté la victoire.* » — 2 Chr 20:21-22",
    "🌺 « *Deux fois dans l'obscurité de la foi — mais tu as dit comme Job : quand il m'aura éprouvé, je sortirai comme l'or.* » — Job 23:10",
    "💡 « *Deux fois la tristesse a menacé ton âme — mais tu as trouvé ta force en l'Éternel ton Dieu.* » — 1 Sam 30:6",
    "🎯 « *Deux fois le serpent a cherché à te mordre — mais tu as marché sur sa tête au nom de Jésus.* » — Luc 10:19",
    "🌈 « *Deux fois la main de Dieu t'a caché dans le creux du rocher pendant la tempête.* » — Ex 33:22",
    "🦅 « *Deux fois dans les filets de l'ennemi — et deux fois l'Éternel les a rompus.* » — Ps 124:7",
    "🌅 « *Deux fois l'hiver de l'âme — mais après deux hivers, le printemps de la victoire fleurit.* » — Cant 2:11",
    "⭐ « *Deux fois dans la tempête — et deux fois tu as entendu : Paix, tais-toi !* » — Marc 4:39",
    "💎 « *Deux fois la flèche de l'adversité t'a visé — et deux fois le bouclier de la foi a protégé.* » — Éph 6:16",
    "🏆 « *Deux épreuves franchies — deux preuves que Dieu est avec toi.* » — És 43:2",
    "🎁 « *Après deux combats, Dieu te donne un témoignage qui vaut deux fois plus.* » — Ps 34:3",
    "🌊 « *Deux fois le fleuve a été difficile à traverser — et deux fois l'Éternel a arrêté les eaux.* » — Jos 3:16",
    "🔑 « *Deux fois dans la salle d'attente de Dieu — et deux fois Il t'a reçu au bon moment.* » — Ps 27:14",
    "✨ « *Deux fois dans le feu qui consume — et deux fois tu en es sorti sans odeur de brûlé.* » — Dan 3:27",
    "🎶 « *Après deux victoires difficiles, ton cantique a la profondeur que seul R2 peut donner.* » — Ps 40:3",
    "🌻 « *Dieu ne t'a pas abandonné au R2. Il t'a simplement poussé à aller plus haut.* » — Phil 3:14",
    "🏅 « *Deux fois blessé, deux fois guéri — et maintenant tu portes les cicatrices de la foi.* » — 1 Pi 2:24",
    "🙌 « *Deux fois la défaite semblait certaine — et deux fois la victoire de l'Éternel est arrivée.* » — 2 Cor 2:14",
    "🔆 « *Deux fois dans le creux — mais chaque fois, Dieu t'a conduit au sommet.* » — Ps 40:2",
    "🌠 « *La victoire au R2 est le témoignage que Dieu est fidèle même quand la route est longue.* » — Ps 92:15",
    "⚡ « *Deux rounds de foi — et la couronne de vie t'appartient doublement.* » — Jac 1:12",
    "💪 « *Deux fois la montagne s'est dressée devant toi — et deux fois tu l'as déplacée par la foi.* » — Matt 17:20",
    "🎉 « *Après deux combats gagnés, ta foi est devenue une forteresse inébranlable.* » — Ps 61:4",
]

# ═══════════════════════════════════════════════════════════════════
#  ✅3️⃣  GAGNÉ R3 — Victoire ultime après trois épreuves
# ═══════════════════════════════════════════════════════════════════
PAROLES_GAGNE_R3 = [
    "🔥 « *Shadrach, Meshach et Abed-Nego sont entrés dans la fournaise ardente — et en sont sortis victorieux ! Toi aussi !* » — Dan 3:25",
    "🏆 « *Trois fois Paul a demandé la délivrance — et Dieu a dit : ma grâce te suffit. Et tu as gagné quand même !* » — 2 Cor 12:8-9",
    "⭐ « *Trois fois Pierre a nié, mais Jésus l'a restauré trois fois aussi. Ta triple épreuve est vaincue.* » — Jn 21:17",
    "💪 « *Trois fois Samson fut tenté par Dalila, mais sa force ultime vint de Dieu. Tu es comme lui.* » — Jug 16:28",
    "🌟 « *Jonas a passé trois jours dans le ventre du poisson — et en est sorti victorieux. Tu en es sorti aussi !* » — Jon 1:17",
    "🌈 « *Trois jours dans le tombeau, mais la résurrection est venue ! Ta victoire en R3 est une résurrection !* » — Matt 28:6",
    "🎯 « *Trois fois Gédéon a tenu bon, et Dieu a dispersé l'armée ennemie. Loue l'Éternel !* » — Jug 7:21",
    "💡 « *Après trois rondes, Dieu t'a accordé la victoire. C'est le signe de la Trinité — Père, Fils, Esprit !* » — Matt 28:19",
    "🌺 « *Élie a versé de l'eau sur l'autel trois fois, et le feu est quand même tombé. Ta victoire est celle du feu divin !* » — 1 Rois 18:34-38",
    "🦅 « *Trois fois dans l'adversité, mais trois fois Dieu t'a défendu. Tu es son champion !* » — Ps 91:14",
    "🌅 « *Trois fois dans la nuit, mais l'aurore est venue. Tu as vu l'aurore de Dieu !* » — Ps 30:6",
    "💎 « *L'or est éprouvé trois fois au creuset — et tu es resssorti victorieux. Tu es de l'or pur !* » — 1 Pi 1:7",
    "🎁 « *Trois fois la porte semblait fermée, mais au troisième coup elle s'est ouverte. C'est le timing de Dieu.* » — Luc 18:5",
    "🌊 « *Les trois amis de Job ont dit que Dieu l'avait abandonné — mais Dieu a restauré Job. Gloire !* » — Job 42:10",
    "🔑 « *Après trois demandes, le Père a dit oui — parce que ta foi a traversé toutes les tempêtes.* » — Matt 7:8",
    "✨ « *Trois fois tu as lutté, trois fois tu as persisté — et Dieu t'a couronné.* » — Jac 1:12",
    "🎶 « *C'est en passant par le feu et par l'eau que tu es entré dans une large aisance.* » — Ps 66:12",
    "🌻 « *Job a tout perdu trois fois mais Dieu l'a béni au double. Ta victoire vaut triple !* » — Job 42:10",
    "🏅 « *Trois jours de marche dans le désert avant de trouver de l'eau. Tu as trouvé ton eau !* » — Ex 15:22-25",
    "🙌 « *Trois fois nu dans la tempête avec Paul, et trois fois Dieu a dit : il n'y aura pas de perte.* » — Ac 27:24",
    "🔆 « *Après la triple épreuve, la triple bénédiction t'appartient.* » — Deut 28:2",
    "🌠 « *Trois fois dans la détresse, trois fois l'Éternel m'a délivré. Loue son nom !* » — Ps 107:6",
    "⚡ « *Tu as passé par le feu et par l'eau, mais l'Éternel t'a fait sortir au large.* » — Ps 66:12",
    "💪 « *Après trois jours de jeûne, Esther est allée devant le roi et a obtenu la victoire.* » — Est 5:2",
    "🎉 « *Trois fois Dieu a éprouvé ta foi, et trois fois tu n'as pas lâché. Tu mérites la couronne !* » — 2 Tim 4:8",
    "🌟 « *Trois fois dans la fournaise — et le quatrième était là avec toi. Dieu ne t'a jamais quitté.* » — Dan 3:25",
    "🎊 « *Après trois rondes, la victoire a la saveur de l'éternité. Goûte-la !* » — Ps 34:9",
    "🔥 « *Trois fois l'ennemi a dit : tu ne gagneras pas. Et trois fois Dieu a dit : si, Il gagnera !* » — Rom 8:37",
    "🌺 « *Trois rondes, trois tentatives — et Dieu t'a honoré. C'est un témoignage !* » — 1 Sam 17:45",
    "💡 « *Le troisième jour, les noces de Cana ont eu lieu — et l'eau est devenue vin. Ta victoire est un miracle !* » — Jn 2:1",
    "🎯 « *Trois fois tombé, trois fois relevé — et la quatrième fois, tu as gagné debout !* » — Prov 24:16",
    "🌈 « *Trois fois la pluie n'est pas venue, mais la septième fois le nuage est apparu. En R3, ton nuage est venu.* » — 1 Rois 18:44",
    "🦅 « *Trois fois dans le ventre de la baleine — mais la prière d'au fond a été entendue.* » — Jon 2:2",
    "🌅 « *Après trois rondes de persévérance, ta foi a vaincu le monde.* » — 1 Jn 5:4",
    "⭐ « *Dieu a attendu le troisième round pour révéler toute sa gloire dans ta victoire.* » — Jn 11:4",
    "💎 « *Trois fois dans le creuset — tu en es sorti comme de l'argent affiné.* » — Zach 13:9",
    "🏆 « *Après trois épreuves consécutives, ta victoire vaut dix fois plus. Savoure !* » — Dan 1:20",
    "🎁 « *Trois fois dans l'obscurité, mais la lumière de l'Éternel ne s'est jamais éteinte.* » — Ps 119:105",
    "🌊 « *Trois fois submergé par les vagues, mais l'Éternel t'a tendu la main à chaque fois.* » — Matt 14:31",
    "🔑 « *Trois demandes pressantes — et Dieu a finalement dit : Oui, mon enfant, entre !* » — Luc 11:8",
    "✨ « *Trois fois dans la vallée de la mort, mais tu n'as craint aucun mal car Il était avec toi.* » — Ps 23:4",
    "🎶 « *Triple épreuve, triple victoire. Car l'Éternel est Dieu des armées.* » — 1 Sam 17:45",
    "🌻 « *Après le troisième essai, Dieu a ouvert les cieux sur toi.* » — Mal 3:10",
    "🏅 « *Tu as combattu le bon combat trois fois — maintenant la couronne de justice t'est réservée.* » — 2 Tim 4:7-8",
    "🙌 « *Trois rondes de foi et Jéricho est tombée. Ta victoire est la chute de Jéricho !* » — Jos 6:20",
    "🔆 « *Trois fois dans le désert avec Moïse — mais la Terre Promise est toujours là.* » — Ex 3:17",
    "🌠 « *Triple persévérance, triple récompense. C'est le calcul de Dieu.* » — Jac 1:12",
    "⚡ « *Trois fois dans la nuit sans étoiles, mais l'aurore a toujours le dernier mot.* » — Ps 30:6",
    "💪 « *Tu as marché trois fois autour du problème comme Israël a marché autour de Jéricho — et les murs sont tombés !* » — Jos 6:15",
    "🎉 « *Trois épreuves pour un seul trophée — mais quel trophée ! La victoire de Dieu !* » — 2 Cor 2:14",
    "🌟 « *Trois fois Dieu a dit : c'est assez. Mais Il t'a quand même conduit à la victoire.* » — 2 Cor 12:8-9",
    "🎊 « *La triple épreuve révèle la triple grâce de Dieu. Père — Force. Fils — Victoire. Esprit — Joie.* » — Matt 28:19",
    "🔥 « *Tu as supporté le triple feu de la tribulation. Tu es maintenant de l'or pur.* » — Mal 3:3",
    "🌺 « *Trois fois dans les flammes et le quatrième homme était là. Il était là pour toi aussi.* » — Dan 3:25",
    "💡 « *Après le troisième essai, Dieu a montré que rien n'est impossible à celui qui croit.* » — Luc 1:37",
    "🎯 « *Ta persévérance de trois rondes a édifié ta foi comme une montagne.* » — Matt 17:20",
    "🌈 « *Trois fois dans l'abîme — et trois fois Dieu a ouvert le chemin du retour.* » — Jon 2:7",
    "🦅 « *La foi qui traverse trois épreuves est la foi qui déplace les montagnes.* » — Marc 11:23",
    "🌅 « *Après le troisième rattrapage, l'Éternel t'a accordé le repos de la victoire.* » — Ex 33:14",
    "⭐ « *Trois fois dans la fournaise — tu en es sorti sans odeur de feu. Gloire à Dieu !* » — Dan 3:27",
    "💎 « *Ta foi triomphante en R3 est un témoignage qui durera éternellement.* » — Héb 11:6",
    "🌻 « *Trois fois dans le désert et trois fois l'eau est sortie du rocher. Dieu ne manque jamais.* » — Ex 17:6",
    "🎶 « *Après la triple nuit, le matin de Pâques est venu. Ta victoire est une résurrection.* » — Matt 28:1",
    "🔆 « *Trois cycles de foi — trois preuves que Dieu est fidèle à sa parole.* » — 2 Tim 2:13",
    "🌟 « *Trois fois Abraham a obéi sans comprendre — et trois fois Dieu lui a confirmé sa bénédiction.* » — Gen 12:1",
    "🔥 « *Trois fois dans la gueule du lion comme Daniel — et trois fois Dieu a fermé les mâchoires.* » — Dan 6:22",
    "💪 « *Trois jours sous la terre comme Jonas — et au troisième jour, la délivrance est venue !* » — Jon 1:17",
    "🌈 « *Trois fois Gédéon a demandé la confirmation de Dieu — et trois fois Il a répondu.* » — Jug 6:36-40",
    "🎯 « *Trois fois Pierre a affirmé son amour — et trois fois Jésus lui a dit : vas et fais paître mes brebis.* » — Jn 21:15-17",
    "💡 « *Trois fois dans la fournaise avec Shadrach — et le quatrième homme était toujours présent.* » — Dan 3:25",
    "🌺 « *Trois fois Balaam a voulu maudire Israël — et trois fois Dieu a transformé la malédiction en bénédiction.* » — Nomb 23:11",
    "🦅 « *Trois fois Pierre a renié — mais trois fois Jésus l'a restauré avec amour.* » — Jn 21:17",
    "🌅 « *Trois jours de deuil avec Esther — et au troisième jour, le roi a tendu son sceptre.* » — Est 5:2",
    "💎 « *Trois fois dans le désert avec Israël — et trois fois Dieu a pourvu à leurs besoins.* » — Nomb 14:22",
    "🎁 « *Trois fois dans la fournaise du service de Paul — et trois fois Dieu a dit : ma grâce suffit.* » — 2 Cor 12:9",
    "🌊 « *Trois fois l'ange a résisté à Daniel — et au bout de trois semaines, la réponse est venue.* » — Dan 10:13",
    "🔑 « *Trois jours de jeûne avec Esdras — et Dieu a protégé le voyage de Jérusalem à Babylone.* » — Esd 8:23",
    "✨ « *Trois fois dans la vallée de l'ombre — mais tu n'as craint aucun mal car IL était avec toi.* » — Ps 23:4",
    "🎶 « *Trois fois la vigne a semblé stérile — mais au troisième an, elle a produit son fruit.* » — Luc 13:8",
    "🌻 « *Trois fois la tempête a soufflé sur ta foi — et trois fois ta foi a résisté comme un roc.* » — Matt 7:25",
    "🏅 « *Trois fois tu as prié dans le jardin de Gethsémani — et l'ange t'a fortifié.* » — Luc 22:43",
    "🙌 « *Trois fois sous la croix pesante — mais Simon de Cyrène a aidé. Dieu envoie des secours.* » — Luc 23:26",
    "🔆 « *Trois fois dans l'abîme de la trahison — mais Dieu a ressuscité ce que les hommes ont tué.* » — Ac 2:24",
    "🌠 « *Trois fois dans l'obscurité totale — mais au troisième jour, la lumière de la résurrection est arrivée.* » — Matt 28:1",
    "⚡ « *Trois fois la foi a semblé inutile — mais au troisième essai, les montagnes se sont déplacées.* » — Marc 11:23",
    "💪 « *Trois fois tu t'es relevé de la poussière — et chaque fois Dieu t'a mis dans un lieu plus élevé.* » — Ps 113:7",
    "🎉 « *Trois fois dans le ventre du désespoir — mais l'Éternel a commandé au poisson de te recracher sur le rivage.* » — Jon 2:11",
    "🌟 « *Trois rondes de foi — trois monuments à la gloire de Dieu dans ta vie.* » — Jos 4:7",
    "🎊 « *Trois fois l'ennemi a dit : c'est impossible. Trois fois Dieu a dit : avec moi, rien n'est impossible.* » — Luc 1:37",
    "🔥 « *Trois fois dans la détresse de Jehoshaphat — et trois fois l'Éternel a combattu à sa place.* » — 2 Chr 20:17",
    "🌺 « *Trois fois Samson a failli — mais sa dernière prière a été la plus puissante.* » — Jug 16:28",
    "💡 « *Trois nuits avec la femme en deuil — et au troisième jour Élisée a rendu la vie à l'enfant.* » — 2 Rois 4:35",
    "🎯 « *Trois fois le serviteur de Géhazi n'a rien vu — mais Élisée a prié et les yeux ont été ouverts.* » — 2 Rois 6:17",
    "🌈 « *Trois fois dans le désert de la solitude — mais la promesse de la Terre Promise tenait toujours.* » — Deut 6:3",
    "🦅 « *Trois fois le faucon tombe avant d'apprendre à voler. Tu as appris à voler en R3 !* » — És 40:31",
    "🌅 « *Trois fois dans la nuit de la confusion — et au matin, la direction de Dieu était claire.* » — Ps 143:8",
    "⭐ « *Trois fois les ennemis ont dit : il est tombé pour toujours. Et trois fois tu t'es relevé.* » — Mic 7:8",
    "💎 « *Trois fois l'argent a été affiné — et le résultat est plus pur que jamais. C'est toi.* » — Zach 13:9",
    "🏆 « *Trois épreuves — trois couronnes. Car chaque épreuve passée est une couronne gagnée.* » — 2 Tim 4:8",
    "🎁 « *Après trois nuits de pleurs dans la prison, Paul et Silas ont chanté — et les portes se sont ouvertes.* » — Ac 16:25-26",
    "🌊 « *Trois fois dans les eaux profondes — et trois fois la corde de la grâce t'a ramené au rivage.* » — Ps 18:17",
    "🔑 « *Trois fois la porte semblait close à jamais — mais Dieu a ouvert ce qu'aucun homme ne peut fermer.* » — Apo 3:7",
    "✨ « *Trois fois le combat a semblé inégal — mais avec Dieu, la minorité est toujours la majorité.* » — 2 Rois 6:16",
    "🎶 « *Trois fois dans la vallée de Josaphat — et trois fois Dieu a dit : la bataille n'est pas vôtre mais à moi.* » — 2 Chr 20:15",
    "🌻 « *Trois fois la tempête du siècle a frappé — et trois fois l'arche de Noé a flotté sur les eaux.* » — Gen 7:17",
    "🏅 « *Trois fois dans la géhenne des hommes — mais tu appartiens au Dieu qui a vaincu la mort.* » — Apo 1:18",
    "🙌 « *Trois fois sur le chemin de Damas — et la voix de Dieu t'a touché.* » — Ac 9:3-6",
    "🔆 « *Trois fois au bord du précipice — et trois fois la main invisible de Dieu t'a retenu.* » — Ps 73:23",
    "🌠 « *Trois fois sous le joug de l'ennemi — et trois fois le Sauveur a brisé le joug.* » — És 9:4",
    "⚡ « *Trois fois dans le creuset de la pauvreté — mais Dieu est le Dieu de la multiplication.* » — 2 Rois 4:7",
    "💪 « *Trois fois la montagne de Sion a tremblé — mais les fondations posées par Dieu ne tremblent pas.* » — Ps 125:1",
    "🎉 « *Trois fois dans la fournaise — et tu en es sorti sans même l'odeur du feu. C'est le miracle du R3 !* » — Dan 3:27",
    "🌟 « *Trois fois les oiseaux ont mangé le pain — mais Dieu a toujours fourni plus que suffisant.* » — Matt 6:26",
    "🎊 « *Après trois rondes de tribulation, Paul a dit : je peux tout par Christ. C'est vrai pour toi aussi.* » — Phil 4:13",
    "🔥 « *Trois fois dans la fournaise de l'impatience — mais tu as attendu l'Éternel et tu as renouvelé ta force.* » — És 40:31",
    "🌺 « *Trois fois l'ennemi a dressé un piège — et trois fois Dieu l'a déjoué.* » — Ps 91:3",
    "💡 « *Trois fois la parole de Dieu s'est accomplie malgré les obstacles. Ta victoire R3 est parole accomplie !* » — És 55:11",
    "🎯 « *Trois fois tu as dit : non je ne lâche pas. Et Dieu a dit : c'est bien, je t'accorde ta demande.* » — Gen 32:26",
    "🌈 « *Trois fois dans le tunnel sans lumière — mais la lumière du troisième jour a tout illuminé.* » — Jn 11:44",
    "🦅 « *Trois fois le soldat de la foi s'est levé — et la troisième fois, l'armée ennemie a fui.* » — 2 Chr 14:12",
    "🌅 « *Après trois rondes de nuit, l'aurore du R3 est d'autant plus glorieuse.* » — Ps 30:6",
    "⭐ « *Trois fois la honte a frappé — mais la grâce de Dieu t'a restauré à chaque fois.* » — 2 Sam 12:13",
    "💎 « *Trois épreuves traversées — trois témoignages de la fidélité de Dieu.* » — Ps 92:15",
    "🏆 « *Ta triple victoire est la preuve que tu appartiens à Dieu — et que Dieu ne perd jamais.* » — 1 Cor 15:57",
    "🎁 « *Trois fois dans la vallée de Baca — et trois fois les sources de bénédiction ont jailli.* » — Ps 84:7",
    "🌊 « *Trois fois au bord de la mer Rouge — et trois fois Dieu a dit : avance, je vais agir.* » — Ex 14:15",
    "🔑 « *Après trois nuits de larmes, la joie du matin du R3 vaut une vie entière.* » — Ps 30:6",
    "✨ « *Trois fois tu as résisté à la tentation de renoncer — et Dieu t'a dit : c'est assez, tu as gagné.* » — Jac 4:7",
    "🎶 « *Trois fois le cantique de louange a brisé les chaînes — et au R3, les portes se sont ouvertes.* » — Ac 16:26",
    "🌻 « *Ta foi de trois rondes a édifié une fondation indestructible pour ta vie.* » — Matt 7:24",
    "🏅 « *Trois fois dans l'obscurité — mais la lampe de Dieu n'a jamais été soufflée.* » — 2 Sam 22:29",
    "🙌 « *Trois fois la parole de découragement t'a frappé — mais la Parole de Dieu t'a fortifié.* » — Héb 4:12",
    "🔆 « *La triple victoire est le signe que Dieu t'a oint pour quelque chose de grand.* » — Ps 84:12",
    "🌠 « *Trois fois l'impossible s'est dressé devant toi — et trois fois Dieu a fait des possibles avec tes impossibles.* » — Luc 1:37",
    "⚡ « *Trois fois dans le lion — mais la main de l'Éternel a fermé les gueules de l'adversité.* » — Dan 6:22",
    "💪 « *Après trois combats, tu sors plus fort, plus sage et plus proche de Dieu. C'est le prix du R3.* » — Job 23:10",
    "🎉 « *Trois rondes de foi victorieuses — trois témoignages éternels de la bonté de Dieu.* » — Ps 107:2",
    "🌟 « *Ta victoire en R3 est le sceau de Dieu sur ta vie. Il t'a marqué comme sien.* » — Éph 1:13",
    "🌺 « *Trois fois dans le feu — et tu en es sorti avec l'odeur de la présence de Dieu.* » — Dan 3:25",
    "🏆 « *Trois rounds franchis — Dieu t'a accordé la victoire ultime. Gloire à Son nom !* » — 1 Chr 29:11",
]

# ═══════════════════════════════════════════════════════════════════
#  ❌  PERDU — Confort, compassion, encouragement
# ═══════════════════════════════════════════════════════════════════
PAROLES_PERDU = [
    "🤍 « *L'Éternel est proche de ceux qui ont le cœur brisé, et il sauve ceux qui ont l'esprit dans l'abattement.* » — Ps 34:19",
    "🌿 « *Il guérit ceux qui ont le cœur brisé, et il bande leurs blessures.* » — Ps 147:3",
    "☁️ « *Les pleurs durent une nuit, mais la joie vient le matin.* » — Ps 30:6",
    "🕊️ « *Venez à moi, vous qui êtes fatigués et chargés, et je vous donnerai du repos.* » — Matt 11:28",
    "🌱 « *Ce que tu vis maintenant n'est pas la fin. C'est un nouveau commencement.* » — Apo 21:5",
    "💙 « *Je sais que les pensées que j'ai à votre égard sont des pensées de paix.* » — Jér 29:11",
    "🌤️ « *Il ne cassera pas le roseau froissé, il n'éteindra pas le lumignon qui faiblit.* » — És 42:3",
    "🙏 « *Confie-toi en l'Éternel de tout ton cœur, et ne t'appuie pas sur ta sagesse.* » — Prov 3:5",
    "🌿 « *L'Éternel est bon, il est un refuge au jour de la détresse.* » — Nah 1:7",
    "💜 « *Je t'ai aimé d'un amour éternel; c'est pourquoi je te conserve ma bienveillance.* » — Jér 31:3",
    "🌦️ « *Ne te réjouis pas à mon sujet, mon ennemie ! Car si je suis tombée, je me relèverai.* » — Mic 7:8",
    "🕊️ « *L'Éternel est mon berger: je ne manquerai de rien.* » — Ps 23:1",
    "🌻 « *Tu ne seras jamais éprouvé au-delà de tes forces. Il y a toujours une issue.* » — 1 Cor 10:13",
    "🌱 « *Dieu fait concourir toutes choses au bien de ceux qui l'aiment.* » — Rom 8:28",
    "💚 « *Cette légère et momentanée tribulation nous prépare un poids éternel de gloire.* » — 2 Cor 4:17",
    "🌊 « *Quand tu traverses les eaux, je suis avec toi. Ne crains pas.* » — És 43:2",
    "🕊️ « *Dieu essuiera toute larme de leurs yeux. La douleur aura une fin.* » — Apo 21:4",
    "🌿 « *Il donne de la force à celui qui est fatigué, et il augmente la vigueur de celui qui est à bout de forces.* » — És 40:29",
    "☁️ « *Tu n'es pas abandonné. Dieu connaît le chemin que tu fais.* » — Job 23:10",
    "💙 « *Je marcherai au milieu de la détresse, tu me feras revivre.* » — Ps 138:7",
    "🌤️ « *L'Éternel est proche de tous ceux qui l'invoquent, de tous ceux qui l'invoquent avec sincérité.* » — Ps 145:18",
    "🙏 « *Portez les fardeaux les uns des autres, et accomplissez ainsi la loi de Christ.* » — Gal 6:2",
    "💜 « *Car l'Éternel ne rejette pas pour toujours. S'il afflige, il fait aussi miséricorde.* » — Lam 3:31-32",
    "🌱 « *Il n'a point de pouvoir sur toi pour te renverser. Tu te relèveras.* » — Prov 24:16",
    "🌿 « *La tristesse du soir fait place à la joie du matin. Tiens bon !* » — Ps 30:6",
    "💚 « *Dieu est notre refuge et notre force, un secours qui ne manque jamais dans la détresse.* » — Ps 46:2",
    "🌊 « *Il ne te laissera pas tomber. Il tient ta main droite.* » — Ps 73:23",
    "☁️ « *Tu souffres aujourd'hui, mais Dieu prépare quelque chose de plus grand pour demain.* » — Rom 8:18",
    "🕊️ « *La paix de Dieu, qui surpasse toute intelligence, gardera vos cœurs.* » — Phil 4:7",
    "🌤️ « *Ce n'est pas la fin. C'est seulement un tournant. Dieu est le Dieu des nouveaux départs.* » — És 43:19",
    "💙 « *L'Éternel t'a vu tomber. Il t'a vu pleurer. Il te relève maintenant.* » — Ps 145:14",
    "🙏 « *Jetez sur lui tous vos soucis, car lui-même prend soin de vous.* » — 1 Pi 5:7",
    "🌻 « *Ne perds pas ta confiance en Dieu, car elle a une grande récompense.* » — Héb 10:35",
    "💜 « *La chute du juste n'est pas définitive. Il se relèvera par la grâce de Dieu.* » — Mic 7:8",
    "🌱 « *L'Éternel rachètera tous tes efforts perdus. Il ne laisse rien en vain.* » — Joël 2:25",
    "🌿 « *Tu es brisé mais pas détruit. Tu es renversé mais pas abattu.* » — 2 Cor 4:9",
    "💚 « *Dieu est le Père des miséricordes et le Dieu de toute consolation.* » — 2 Cor 1:3",
    "🌊 « *Même si tu passes par la vallée de l'ombre de la mort, Il est avec toi.* » — Ps 23:4",
    "☁️ « *Après la tempête, l'arc-en-ciel. Après la défaite, la renaissance.* » — Gen 9:13",
    "🕊️ « *L'Éternel rachète l'âme de ses serviteurs, et tous ceux qui l'espèrent ne seront pas condamnés.* » — Ps 34:23",
    "🌤️ « *Ne te décourage pas dans le bien, car au temps convenable vous moissonnerez si vous ne vous lassez pas.* » — Gal 6:9",
    "💙 « *Il te fortifie et te garde de tout mal. Sa main est sur toi même dans la défaite.* » — 2 Thes 3:3",
    "🙏 « *Je suis venu pour guérir les cœurs brisés. Laisse Jésus guérir le tien.* » — Luc 4:18",
    "💜 « *L'Éternel est lent à la colère et plein de bonté. Il a de la compassion pour toi.* » — Ps 103:8",
    "🌱 « *Il élève le pauvre de la poussière, et le misérable du fumier, pour les faire asseoir avec les princes.* » — Ps 113:7-8",
    "🌿 « *Dieu n'a pas oublié ta douleur. Il a mis tes larmes dans son outre.* » — Ps 56:9",
    "💚 « *Je restaurerai ce qui a été perdu. Je donnerai en échange de la honte une double portion.* » — És 61:7",
    "🌊 « *Même si ton esprit défaille en toi, c'est Dieu qui connaît ton chemin.* » — Ps 142:4",
    "☁️ « *La douleur d'une nuit s'efface à l'aurore. L'Éternel prépare ton matin.* » — Ps 30:6",
    "🕊️ « *Heureux ceux qui pleurent, car ils seront consolés.* » — Matt 5:4",
    "🌤️ « *Ceux qui sèment avec larmes moissonneront avec chants d'allégresse.* » — Ps 126:5",
    "💙 « *Il relève ceux qui sont courbés, il aime les justes.* » — Ps 146:8",
    "🙏 « *L'Éternel se souvient de nous, il bénira. Il fortifiera les petits et les grands.* » — Ps 115:12",
    "🌻 « *Dieu est proche des humbles de cœur. Il ne méprise pas ta douleur.* » — Ps 34:19",
    "💜 « *Après la pluie vient le soleil. Après la défaite vient la leçon qui te mène à la victoire.* » — Ps 19:10",
    "🌱 « *Tous les chemins de l'Éternel sont miséricorde et fidélité pour ceux qui gardent son alliance.* » — Ps 25:10",
    "🌿 « *Tu as été blessé pour être guéri. Tu as chuté pour mieux t'envoler.* » — Os 6:1",
    "💚 « *L'Éternel te rendra le double de ce qui a été pris.* » — Joël 2:25",
    "🌊 « *Il t'a vu dans ta détresse — et il n'a pas détourné son visage. Il a entendu.* » — Ps 22:25",
    "☁️ « *Je t'ai aimé d'un amour éternel. Ta défaite ne change rien à cet amour.* » — Jér 31:3",
    "🕊️ « *Ne pleure pas — Dieu transforme les larmes en perles de victoire future.* » — Apo 21:4",
    "🌤️ « *Fortifiez vos mains languissantes et vos genoux qui chancellent.* » — Héb 12:12",
    "💙 « *La prière sincère du juste est très puissante. Prie après cette défaite.* » — Jac 5:16",
    "🙏 « *Dieu prend soin de toi même dans la défaite. Il n'a pas abandonné son plan pour toi.* » — Jér 29:11",
    "🌿 « *L'Éternel ne laisse pas tomber ses enfants. Il récompense ceux qui persistent.* » — Héb 11:6",
    "💙 « *Ne sois pas abattu car l'Éternel ton Dieu est avec toi partout où tu iras.* » — Jos 1:9",
    "🌸 « *Même si tu trébuchais, tu ne tomberas pas car l'Éternel soutient ta main.* » — Ps 37:24",
    "☀️ « *Après la pluie de cette défaite, l'arc-en-ciel de ta prochaine victoire s'approche.* » — Gen 9:13",
    "🌿 « *L'Éternel est juste dans toutes ses voies. Cette défaite aussi a un sens dans son plan.* » — Ps 145:17",
    "💙 « *Dieu ne méprise pas un cœur brisé et contrit. Il est près de toi maintenant.* » — Ps 51:19",
    "🌱 « *Regarde, je fais une chose nouvelle. Elle germe déjà — ne la vois-tu pas ?* » — És 43:19",
    "🕊️ « *Le Seigneur bande les blessures des cœurs brisés. Il guérit en ce moment.* » — Ps 147:3",
    "🌤️ « *Je t'ai aimé d'un amour éternel. Même dans cette défaite, mon amour ne change pas.* » — Jér 31:3",
    "💜 « *Si Dieu est pour nous, qui sera contre nous ? Cette défaite n'est pas ta fin.* » — Rom 8:31",
    "☁️ « *Dieu transforme les défaites en victoires futures. Il fait concourir tout à ton bien.* » — Rom 8:28",
    "🌊 « *Ta larme a été mise dans son outre. Il n'a rien oublié de ta souffrance.* » — Ps 56:9",
    "🙏 « *Ne te réjouis pas de ma chute, ô mon ennemie ! Je me relèverai car l'Éternel est ma lumière.* » — Mic 7:8",
    "🌻 « *Soyez sans inquiétude. Dieu veille sur chaque défaite et prépare la victoire suivante.* » — Phil 4:6",
    "💚 « *L'Éternel ne rejette pas pour toujours. Si il permet la défaite, la restauration suit.* » — Lam 3:31",
    "🌦️ « *Tu peux faire confiance à Dieu dans cette douleur. Il tient ce qu'il promet.* » — Nomb 23:19",
    "🕊️ « *Même quand le figuier ne fleurit pas, je me réjouirai en l'Éternel mon Sauveur.* » — Hab 3:17-18",
    "🌤️ « *Dieu est fidèle et ne permettra pas que tu sois tenté au-delà de tes forces.* » — 1 Cor 10:13",
    "💙 « *L'Éternel fera justice à son élu. Ne te décourage pas.* » — Luc 18:7",
    "🌱 « *Cette légère défaite prépare un poids éternel de gloire. Garde les yeux sur l'éternité.* » — 2 Cor 4:17",
    "🌿 « *David a pleuré après sa défaite face à Goliath la première fois — et il s'est relevé.* » — 1 Sam 17:37",
    "💜 « *La tristesse selon Dieu produit une repentance qui mène au salut. Cette défaite te rapproche.* » — 2 Cor 7:10",
    "☁️ « *Job a tout perdu — mais il a dit : l'Éternel a donné, l'Éternel a repris. Béni soit l'Éternel.* » — Job 1:21",
    "🌊 « *Quand tu passes par les eaux je suis avec toi. Cette défaite n'a pas de pouvoir sur toi.* » — És 43:2",
    "🙏 « *L'Éternel est mon rocher et ma délivrance. Après cette défaite, il reste mon rocher.* » — Ps 62:3",
    "🌻 « *Il relève le pauvre de la poussière. Après cette défaite, il te relève.* » — 1 Sam 2:8",
    "💚 « *Ceux qui sèment avec larmes moissonneront avec chants d'allégresse.* » — Ps 126:5",
    "🌦️ « *Ne te décourage pas car au temps convenable tu moissonnes si tu ne te lasses pas.* » — Gal 6:9",
    "🕊️ « *Cette défaite est une école. Elle t'enseigne ce que la victoire ne peut pas enseigner.* » — Héb 12:11",
    "🌤️ « *L'Éternel peut te donner deux fois autant que ce que tu as perdu. Il l'a fait pour Job.* » — Job 42:10",
    "💙 « *Même dans la défaite, tu es plus que vainqueur par celui qui t'a aimé.* » — Rom 8:37",
    "🌱 « *Élargis le lieu de ta tente. Les défaites d'aujourd'hui créent l'espace pour les victoires de demain.* » — És 54:2",
    "🌿 « *Ne perds pas confiance — l'Éternel voit ton effort même quand le résultat te déçoit.* » — Héb 6:10",
    "💜 « *Ton Père céleste connaît tes besoins. Cette défaite ne l'a pas surpris.* » — Matt 6:8",
    "☁️ « *Les pensées de Dieu pour toi sont de paix et non de malheur. Même dans la défaite.* » — Jér 29:11",
    "🌊 « *Dieu est proche de ceux qui sont brisés de cœur. Il est avec toi maintenant.* » — Ps 34:19",
    "🙏 « *Fortifiez vos mains languissantes et vos genoux qui chancellent. Relevez-vous !* » — Héb 12:12",
    "🌻 « *L'Éternel connaît le chemin que je fais. Quand il m'aura éprouvé, je sortirai comme l'or.* » — Job 23:10",
    "💚 « *Cette défaite est une parenthèse — pas une destination. Dieu a une route plus haute pour toi.* » — Prov 3:5-6",
    "🌦️ « *Dieu essuiera toute larme de vos yeux. La douleur n'a pas le dernier mot.* » — Apo 21:4",
    "🕊️ « *Pierre a pleuré amèrement après sa défaite — mais Jésus l'a restauré et l'a nommé chef.* » — Matt 26:75",
    "🌤️ « *Après la défaite du vendredi, le dimanche de la résurrection vient toujours.* » — Jn 20:1",
    "💙 « *La main droite de l'Éternel est la même après la défaite qu'avant. Elle tient encore ta main.* » — Ps 73:23",
    "🌱 « *Toute bonne et parfaite donation vient d'en haut. Ta prochaine bénédiction aussi vient d'en haut.* » — Jac 1:17",
    "🌿 « *L'Éternel s'est souvenu de nous dans notre humiliation. Sa bonté est éternelle.* » — Ps 136:23",
    "💜 « *Dieu ne te laissera pas rester à terre. Sa main est tendue pour te relever.* » — Ps 37:24",
    "☁️ « *Après Gethsémani, la résurrection. Après ta défaite, ta renaissance.* » — Jn 20:19",
    "🌊 « *Ne regarde pas en arrière. Dieu fait une route dans le désert de ta défaite.* » — És 43:19",
    "🙏 « *Paul a connu la disette et l'abondance. Dans les deux cas, il était content grâce à Christ.* » — Phil 4:11-12",
    "🌻 « *Ta défaite n'est pas un abandon de Dieu. C'est un détour vers quelque chose de mieux.* » — Rom 8:28",
    "💚 « *Comme l'argile dans la main du potier, tu es entre les mains de Dieu — même dans la défaite.* » — Jér 18:6",
    "🌦️ « *L'Éternel est la force de mon âme. Même si je trébuche, il me soutient.* » — Ps 27:1",
    "🕊️ « *Jésus n'a pas abandonné Marie au pied de la croix. Il n'abandonnera pas non plus.* » — Jn 19:26",
    "🌤️ « *Après quarante ans de désert avec Moïse, la Terre Promise était là. Ta Terre Promise est là.* » — Jos 1:3",
    "💙 « *Dieu est le Père des orphelins et le juge des veuves. Il voit ta solitude dans la défaite.* » — Ps 68:6",
    "🌱 « *La graine qui meurt produit beaucoup de fruit. Ta défaite est la graine de ta prochaine victoire.* » — Jn 12:24",
    "🌿 « *L'Éternel compte tes larmes. Pas une seule n'est tombée sans être vue.* » — Ps 56:9",
    "💜 « *Si tu tombes sept fois, tu te relèves sept fois car l'Éternel est avec toi.* » — Prov 24:16",
    "☁️ « *Il a caché ma face pendant un moment — mais avec une éternelle bonté il aura compassion.* » — És 54:8",
    "🌊 « *Même dans la défaite, le Seigneur prend soin de toi. Sa miséricorde ne tarit jamais.* » — Lam 3:22",
    "🙏 « *L'Éternel n'est pas loin des cœurs brisés. Sa présence est ta consolation ce soir.* » — Ps 34:19",
    "🌻 « *La semence la mieux arrosée est celle qui a été arrosée de larmes.* » — Ps 126:6",
    "💚 « *Dieu est le Dieu de toute consolation. Il te console dans toutes tes tribulations.* » — 2 Cor 1:3-4",
    "🌦️ « *Ne pleure pas, Dieu a vu ta douleur. Il prépare quelque chose que l'œil n'a pas vu.* » — 1 Cor 2:9",
    "🕊️ « *Dans la défaite aussi, tu es précieux aux yeux de Dieu. Rien ne change cela.* » — És 43:4",
    "🌤️ « *Après la défaite d'Élimélec, Naomi est retournée — et Dieu a préparé Boaz. Ton Boaz arrive.* » — Ruth 2:20",
    "💙 « *Toute la création gémit dans les douleurs — mais la délivrance est certaine.* » — Rom 8:22-23",
    "🌱 « *L'Éternel n'a pas dit que le chemin serait facile — mais il a promis d'être avec toi.* » — Jos 1:9",
    "🌿 « *David pleurait souvent dans les Psaumes — mais chaque Psaume finit en louange. Le tien aussi finira en victoire.* » — Ps 22:25",
    "💜 « *Même Job n'a pas compris pourquoi il souffrait — mais à la fin, Dieu l'a honoré. Tu seras honoré.* » — Job 42:12",
    "☁️ « *L'amour de Christ est si grand qu'il couvre même les défaites. Tu es aimé inconditionnellement.* » — Rom 8:39",
    "🌊 « *Chaque défaite que Dieu permet est une opportunité de voir sa main puissante agir.* » — Ex 14:13",
    "🙏 « *Ne te réjouis pas trop vite, ennemi — car si je suis tombé, je me relèverai !* » — Mic 7:8",
    "🌻 « *La nuit durera peut-être longtemps — mais le matin viendra à coup sûr.* » — Ps 30:6",
    "💚 « *Dieu est le Maître de la seconde chance. Cette défaite n'est pas la dernière page.* » — Joël 2:25",
    "🌦️ « *Garde ton cœur sur ce qui est vrai, honnête, juste — et le Dieu de paix sera avec toi.* » — Phil 4:8-9",
    "🕊️ « *Reste dans la paix de Dieu après cette défaite. Elle surpasse tout entendement.* » — Phil 4:7",
    "🌤️ « *Cette défaite est une invitation à te rapprocher de Dieu. Saisis cette invitation.* » — Jac 4:8",
    "💙 « *L'Éternel est mon berger même dans la vallée sombre. Il me guide au-delà de cette défaite.* » — Ps 23:4",
    "🌱 « *Les larmes d'aujourd'hui arrosent les graines de tes victoires de demain. Continue à semer.* » — Ps 126:5-6",
]

# ═══════════════════════════════════════════════════════════════════
#  MAPPING  statut → liste de paroles
# ═══════════════════════════════════════════════════════════════════
_MAP = {
    'gagne_r0': PAROLES_GAGNE_R0,
    'gagne_r1': PAROLES_GAGNE_R1,
    'gagne_r2': PAROLES_GAGNE_R2,
    'gagne_r3': PAROLES_GAGNE_R3,
    'perdu':    PAROLES_PERDU,
}


def get_parole(statut: str, game_number: int = 0, count: int = 5) -> str:
    """
    Retourne un message avec plusieurs versets bibliques pour le statut donné.

    Paramètres
    ----------
    statut      : 'gagne_r0' | 'gagne_r1' | 'gagne_r2' | 'gagne_r3' | 'perdu'
    game_number : numéro du jeu (affiché dans l'en-tête)
    count       : nombre de versets à inclure (défaut 5)

    Retour
    ------
    Texte Markdown prêt à envoyer, à supprimer après 60 secondes.
    """
    key = statut.lower()
    verses = _MAP.get(key, PAROLES_PERDU)

    # Piocher `count` versets uniques (sans répétition)
    nb = min(count, len(verses))
    selected = random.sample(verses, nb)

    # Retirer les références bibliques (— Ps X:Y) et les marqueurs * d'italique
    def strip_ref(v: str) -> str:
        v = re.sub(r'\s*—\s*[A-Z][^\n»]{1,20}$', '', v, flags=re.MULTILINE)  # retire — Ref
        v = v.replace('*', '')
        return v.rstrip()

    selected = [strip_ref(v) for v in selected]

    prefixes = {
        'gagne_r0': "🏆 **VICTOIRE DIRECTE — La grâce de Dieu !**",
        'gagne_r1': "🌟 **VICTOIRE R1 — La persévérance récompensée !**",
        'gagne_r2': "💪 **VICTOIRE R2 — Deux épreuves, un seul Dieu !**",
        'gagne_r3': "🔥 **VICTOIRE R3 — La foi ultime triomphe !**",
        'perdu':    "🤍 **NE TE DÉCOURAGE PAS — Dieu est encore là !**",
    }
    titre = prefixes.get(key, "🙏 **PAROLE DE DIEU**")

    game_ref = f"_(Jeu **#{game_number}**)_\n" if game_number else ""

    body = "\n\n".join(selected)

    return f"{titre}\n{game_ref}\n{body}{SIGNATURE}"
